In [1]:
import numpy as np

In [4]:
a = []

for i in range(10):
    b = []
    for j in range(10, 20):
        b.append(j)
    a.append(b)

In [7]:
len(a)

10

In [8]:
a

[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [9]:
type(a)

list

In [12]:
array = np.array([1, 2, 3, 4])

In [14]:
array.shape

(4,)

In [16]:
array = np.array([[1], [2], [3]])

In [17]:
array.shape

(3, 1)

In [18]:
array

array([[1],
       [2],
       [3]])

In [19]:
array = np.array([[1,2,3,4]])

In [21]:
array.shape

(1, 4)

In [61]:
array = np.array([[[1, 0], [2, 3], [3, 6]], [[1, 0], [2, 3], [3, 6]], [[1, 0], [2, 3], [3, 6]]], dtype = np.float16)

In [62]:
array

array([[[1., 0.],
        [2., 3.],
        [3., 6.]],

       [[1., 0.],
        [2., 3.],
        [3., 6.]],

       [[1., 0.],
        [2., 3.],
        [3., 6.]]], dtype=float16)

In [40]:
array.shape

(3, 3, 2)

In [64]:
a = [1, 2, 3, 'hello', 2.2, range]

In [68]:
a = np.array(a, dtype = 'str')

In [69]:
a

array(['1', '2', '3', 'hello', '2.2', "<class 'range'>"], dtype='<U15')

In [70]:
print(type(a[0] + a[1]), a[0] + a[1])

<class 'str'> 12


In [75]:
mat = np.full((2, 4), 0.3)

In [76]:
mat

array([[0.3, 0.3, 0.3, 0.3],
       [0.3, 0.3, 0.3, 0.3]])

In [77]:
np.full?

In [80]:
mat = np.full((3, 3), 1)

In [81]:
mat

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [123]:
mat = np.eye(4, k = -1, dtype = np.float16)

In [124]:
mat

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float16)

In [126]:
mat = np.random.random((2, 6))

In [127]:
mat

array([[0.95239195, 0.21308216, 0.99711971, 0.99756167, 0.43032207,
        0.53065677],
       [0.26500844, 0.51729181, 0.06210305, 0.89193247, 0.00690844,
        0.70089327]])

In [134]:
mat = np.random.rand(2, 8, 2)

In [135]:
mat

array([[[0.81313968, 0.2203136 ],
        [0.59192805, 0.73460328],
        [0.31245258, 0.05785384],
        [0.18681147, 0.53493142],
        [0.50502016, 0.89857954],
        [0.26612787, 0.61072047],
        [0.64248596, 0.93384275],
        [0.66824855, 0.31162064]],

       [[0.89551126, 0.55593267],
        [0.66489038, 0.78067239],
        [0.14882602, 0.67414796],
        [0.66457106, 0.8495901 ],
        [0.96661135, 0.34562039],
        [0.44668711, 0.27020831],
        [0.76894615, 0.06240124],
        [0.86257329, 0.0504762 ]]])

In [150]:
mat_random = np.random.randn(2, 8, 2)

In [151]:
mat_random

array([[[-0.83872567, -0.89147847],
        [ 1.19239959, -0.25450628],
        [ 1.47461137,  0.45725392],
        [ 0.61404275,  1.14004368],
        [-0.49523866,  0.01511632],
        [ 0.32130783,  1.01588425],
        [ 2.18648914, -1.31259229],
        [-0.08286917, -1.06846605]],

       [[ 0.89052198,  0.82974856],
        [ 1.65131497, -0.73639237],
        [ 0.33278839, -0.21880415],
        [-0.0404724 ,  1.28128216],
        [-2.14164382,  0.41616118],
        [ 1.07270994,  0.17981272],
        [-2.84449708, -1.5963733 ],
        [-0.50018614,  0.38789506]]])

In [146]:
mat = np.full((2, 3), 0.0)

In [147]:
mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [148]:
mat = np.zeros((2, 3))

In [149]:
mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [152]:
mat = np.zeros_like(mat_random)

In [153]:
mat

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [154]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

In [156]:
print(X.shape, Y.shape)

(2, 2) (2, 2)


In [158]:
print(X + Y, np.add(X, Y))

[[ 6  8]
 [10 12]] [[ 6  8]
 [10 12]]


In [160]:
isinstance(X, np.ndarray)

True

In [161]:
print(X - Y, np.subtract(X, Y))

[[-4 -4]
 [-4 -4]] [[-4 -4]
 [-4 -4]]


In [163]:
print(X*Y, np.multiply(X, Y))

[[ 5 12]
 [21 32]] [[ 5 12]
 [21 32]]


In [165]:
print(np.matmul(X, Y), X@Y)

[[19 22]
 [43 50]] [[19 22]
 [43 50]]


In [167]:
print(np.dot(X, Y))

[[19 22]
 [43 50]]


In [169]:
print(X/Y, np.divide(X, Y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [170]:
print(np.sqrt(X))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [172]:
(mat_random*5) + 10

array([[[ 5.80637166,  5.54260764],
        [15.96199794,  8.72746859],
        [17.37305683, 12.2862696 ],
        [13.07021377, 15.70021842],
        [ 7.52380668, 10.07558161],
        [11.60653917, 15.07942123],
        [20.9324457 ,  3.43703854],
        [ 9.58565417,  4.65766975]],

       [[14.4526099 , 14.14874282],
        [18.25657484,  6.31803814],
        [11.66394193,  8.90597927],
        [ 9.79763801, 16.40641082],
        [-0.70821912, 12.08080589],
        [15.36354968, 10.89906359],
        [-4.22248539,  2.01813352],
        [ 7.49906929, 11.93947532]]])

In [173]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

In [174]:
b = b**2

In [175]:
print(a.shape, b.shape)

(5,) (5,)


In [178]:
np.stack((a, b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [181]:
np.stack((a, b), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [184]:
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [190]:
np.hstack((a, b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [189]:
print(X, Y)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [188]:
print(np.hstack((X, Y))) 
print(np.vstack((X, Y)))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [192]:
print(np.hstack((X, Y)).shape) 
print(np.vstack((X, Y)).shape)

(2, 4)
(4, 2)


In [207]:
print(np.hstack((X, Y)).reshape(4, -1)) 
# print(np.vstack((X, Y)))

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [208]:
a = np.random.randint(0, 20, 3)

In [209]:
a

array([ 2, 10,  5])

In [214]:
choice = np.random.choice(a)

In [215]:
choice

10